export const typeColorMap: Record<string, { text: string; bg: string }> = {
    normal: { text: 'text-gray-600', bg: 'bg-gray-200' },
    fighting: { text: 'text-red-700', bg: 'bg-red-100' },
    flying: { text: 'text-indigo-600', bg: 'bg-indigo-100' },
    poison: { text: 'text-purple-700', bg: 'bg-purple-100' },
    ground: { text: 'text-yellow-800', bg: 'bg-yellow-100' },
    rock: { text: 'text-yellow-900', bg: 'bg-yellow-200' },
    bug: { text: 'text-lime-700', bg: 'bg-lime-100' },
    ghost: { text: 'text-purple-900', bg: 'bg-purple-200' },
    steel: { text: 'text-gray-700', bg: 'bg-gray-100' },
    fire: { text: 'text-red-600', bg: 'bg-red-100' },
    water: { text: 'text-blue-600', bg: 'bg-blue-100' },
    grass: { text: 'text-green-600', bg: 'bg-green-100' },
    electric: { text: 'text-yellow-500', bg: 'bg-yellow-100' },
    psychic: { text: 'text-pink-600', bg: 'bg-pink-100' },
    ice: { text: 'text-blue-400', bg: 'bg-blue-100' },
    dragon: { text: 'text-indigo-800', bg: 'bg-indigo-200' },
    dark: { text: 'text-gray-900', bg: 'bg-gray-300' },
    fairy: { text: 'text-pink-500', bg: 'bg-pink-100' },
    stellar: { text: 'text-indigo-500', bg: 'bg-indigo-100' },
    unknown: { text: 'text-neutral-600', bg: 'bg-neutral-200' },
};
